CREATE TABLE IF NOT EXISTS keyword_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    search_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_keyword_counts_keyword UNIQUE (keyword)
);;

CREATE INDEX IF NOT EXISTS idx_keyword_counts_keyword
    ON keyword_counts (keyword);;

CREATE TABLE IF NOT EXISTS keyword_daily_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    stat_date DATE NOT NULL,
    search_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_keyword_daily_counts_keyword_date UNIQUE (keyword, stat_date)
);;

CREATE INDEX IF NOT EXISTS idx_keyword_daily_counts_stat_date
    ON keyword_daily_counts (stat_date);;
