CREATE TABLE IF NOT EXISTS keyword_counts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    search_count BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uk_keyword_counts_keyword UNIQUE (keyword)
);

CREATE INDEX IF NOT EXISTS idx_keyword_counts_keyword
    ON keyword_counts (keyword);
