CREATE TABLE push_subscriptions (
    id BIGSERIAL PRIMARY KEY,
    device_id BIGINT NOT NULL UNIQUE REFERENCES push_devices(id),
    endpoint VARCHAR(2048) NOT NULL UNIQUE,
    p256dh VARCHAR(512) NOT NULL,
    auth VARCHAR(128) NOT NULL,
    locale VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
