services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: zimdugo-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: zimdugo
      POSTGRES_USER: zimdugo
      POSTGRES_PASSWORD: zimdugo
    volumes:
      - ./docker/postgres/init:/docker-entrypoint-initdb.d:ro

  redis:
    image: redis:7-alpine
    container_name: zimdugo-redis
    ports:
      - "6379:6379"

  elasticsearch:
    build:
      context: .
      dockerfile: ./docker/elasticsearch/Dockerfile
    image: zimdugo-elasticsearch:9.2.6
    container_name: zimdugo-elasticsearch
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.enrollment.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  prometheus:
    profiles:
      - monitoring
    image: prom/prometheus:v3.1.0
    container_name: zimdugo-prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "127.0.0.1:9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    profiles:
      - monitoring
    image: grafana/grafana:11.5.1
    container_name: zimdugo-grafana
    ports:
      - "127.0.0.1:3010:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  elasticsearch-data:
  grafana-storage:
