CREATE EXTENSION IF NOT EXISTS postgis;

DROP EVENT TRIGGER IF EXISTS evt_apply_lockers_postgis_on_create;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(100),
    nickname VARCHAR(50) NOT NULL,
    profile_image_url VARCHAR(255),
    status VARCHAR(20) NOT NULL,
    role VARCHAR(20),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE social_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_user_id VARCHAR(100) NOT NULL,
    provider_email VARCHAR(100),
    provider_profile_image_url VARCHAR(255),
    linked_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_social_account_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_provider_provider_user_id UNIQUE (provider, provider_user_id)
);

CREATE TABLE admin_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    name VARCHAR(50) NOT NULL,
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE admin_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(20) NOT NULL,
    title VARCHAR(255) NOT NULL,
    image_url VARCHAR(500),
    active BOOLEAN DEFAULT FALSE NOT NULL,
    list_order INTEGER DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    applied_at TIMESTAMP(6)
);

CREATE TABLE admin_document_sections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subtitle VARCHAR(255),
    content TEXT NOT NULL,
    list_order INTEGER NOT NULL,
    admin_document_id BIGINT NOT NULL,
    CONSTRAINT fk_admin_document_sections_document FOREIGN KEY (admin_document_id) REFERENCES admin_documents (id)
);

CREATE TABLE admin_document_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_document_id BIGINT NOT NULL,
    language_code VARCHAR(35) NOT NULL,
    title VARCHAR(255) NOT NULL,
    CONSTRAINT fk_admin_document_translations_document FOREIGN KEY (admin_document_id) REFERENCES admin_documents (id),
    CONSTRAINT uk_admin_document_translation_language UNIQUE (admin_document_id, language_code)
);

CREATE TABLE admin_document_section_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    admin_document_section_id BIGINT NOT NULL,
    language_code VARCHAR(35) NOT NULL,
    subtitle VARCHAR(255),
    content TEXT NOT NULL,
    CONSTRAINT fk_admin_document_section_translations_section
        FOREIGN KEY (admin_document_section_id) REFERENCES admin_document_sections (id),
    CONSTRAINT uk_admin_document_section_translation_language UNIQUE (admin_document_section_id, language_code)
);

CREATE TABLE places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    road_address VARCHAR(255),
    CONSTRAINT uk_places_name UNIQUE (name)
);

CREATE TABLE lockers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    road_address VARCHAR(255) NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    place_id BIGINT,
    location geography(Point, 4326) NOT NULL,
    CONSTRAINT fk_lockers_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT chk_lockers_latitude_range CHECK (latitude >= -90 AND latitude <= 90),
    CONSTRAINT chk_lockers_longitude_range CHECK (longitude >= -180 AND longitude <= 180)
);

CREATE TABLE locker_details (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locker_id BIGINT NOT NULL UNIQUE,
    locker_type VARCHAR(30) NOT NULL,
    indoor_outdoor_type VARCHAR(10) NOT NULL,
    ground_level_type VARCHAR(20),
    floor INTEGER,
    min_price INTEGER,
    max_price INTEGER,
    locker_size VARCHAR(100),
    detail_info VARCHAR(1000),
    start_time TIME(6),
    end_time TIME(6),
    image_url VARCHAR(500),
    accurate_vote_count INTEGER NOT NULL,
    inaccurate_vote_count INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_locker_details_locker FOREIGN KEY (locker_id) REFERENCES lockers (id)
);

CREATE TABLE locker_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locker_id BIGINT NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    name VARCHAR(100) NOT NULL,
    road_address VARCHAR(255) NOT NULL,
    detail_info VARCHAR(1000),
    CONSTRAINT fk_locker_translations_locker FOREIGN KEY (locker_id) REFERENCES lockers (id),
    CONSTRAINT uk_locker_translations_locker_language UNIQUE (locker_id, language_code)
);

CREATE TABLE place_translations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    name VARCHAR(120) NOT NULL,
    road_address VARCHAR(255),
    CONSTRAINT fk_place_translations_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_place_translations_place_language UNIQUE (place_id, language_code)
);

CREATE TABLE locker_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    locker_id BIGINT NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    "alias" VARCHAR(255) NOT NULL,
    normalized_alias VARCHAR(255) NOT NULL,
    CONSTRAINT fk_locker_aliases_locker FOREIGN KEY (locker_id) REFERENCES lockers (id),
    CONSTRAINT uk_locker_aliases_locker_normalized UNIQUE (locker_id, normalized_alias)
);

CREATE TABLE place_aliases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    place_id BIGINT NOT NULL,
    language_code VARCHAR(10) NOT NULL,
    "alias" VARCHAR(255) NOT NULL,
    normalized_alias VARCHAR(255) NOT NULL,
    CONSTRAINT fk_place_aliases_place FOREIGN KEY (place_id) REFERENCES places (id),
    CONSTRAINT uk_place_aliases_place_normalized UNIQUE (place_id, normalized_alias)
);

CREATE TABLE favorite_lockers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    locker_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_favorite_lockers_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_favorite_lockers_locker FOREIGN KEY (locker_id) REFERENCES lockers (id),
    CONSTRAINT uk_favorite_lockers_user_locker UNIQUE (user_id, locker_id)
);

CREATE TABLE locker_votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    locker_id BIGINT NOT NULL,
    vote_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_locker_votes_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_locker_votes_locker FOREIGN KEY (locker_id) REFERENCES lockers (id),
    CONSTRAINT uk_locker_votes_user_locker UNIQUE (user_id, locker_id)
);

CREATE TABLE locker_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(100),
    road_address VARCHAR(255),
    ground_level_type VARCHAR(20),
    floor INTEGER,
    indoor_outdoor_type VARCHAR(10) NOT NULL,
    locker_type VARCHAR(30) NOT NULL,
    locker_size VARCHAR(100),
    price_type VARCHAR(20) NOT NULL,
    min_price INTEGER,
    max_price INTEGER,
    additional_info VARCHAR(255),
    operating_time_type VARCHAR(20) NOT NULL,
    start_time TIME(6),
    end_time TIME(6),
    location_consent_agreed BOOLEAN NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    deleted_at TIMESTAMP(6),
    applied_place_id BIGINT,
    applied_locker_id BIGINT,
    reviewed_by VARCHAR(100),
    review_note VARCHAR(1000),
    reviewed_at TIMESTAMP(6),
    CONSTRAINT fk_locker_reports_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE locker_report_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT NOT NULL UNIQUE,
    image_url VARCHAR(500) NOT NULL,
    exif_metadata_json TEXT,
    exif_extracted_at TIMESTAMP(6),
    gps_latitude DOUBLE PRECISION,
    gps_longitude DOUBLE PRECISION,
    gps_altitude DOUBLE PRECISION,
    captured_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_locker_report_images_report FOREIGN KEY (report_id) REFERENCES locker_reports (id)
);

CREATE INDEX IF NOT EXISTS idx_lockers_place_id ON lockers (place_id);
CREATE INDEX IF NOT EXISTS idx_lockers_location_geog ON lockers USING GIST (location);
CREATE UNIQUE INDEX IF NOT EXISTS idx_locker_details_locker_id ON locker_details (locker_id);
CREATE INDEX IF NOT EXISTS idx_locker_aliases_normalized ON locker_aliases (normalized_alias);
CREATE INDEX IF NOT EXISTS idx_place_aliases_normalized ON place_aliases (normalized_alias);
CREATE INDEX IF NOT EXISTS idx_favorite_lockers_user_id ON favorite_lockers (user_id);
CREATE INDEX IF NOT EXISTS idx_favorite_lockers_locker_id ON favorite_lockers (locker_id);
CREATE INDEX IF NOT EXISTS idx_locker_votes_user_id ON locker_votes (user_id);
CREATE INDEX IF NOT EXISTS idx_locker_votes_locker_id ON locker_votes (locker_id);
CREATE INDEX IF NOT EXISTS idx_locker_reports_user_id ON locker_reports (user_id);

CREATE OR REPLACE FUNCTION public.set_lockers_location_from_lat_lng()
RETURNS trigger
LANGUAGE plpgsql
AS
$$
BEGIN
    NEW.location := ST_SetSRID(ST_MakePoint(NEW.longitude, NEW.latitude), 4326)::geography;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_lockers_set_location ON public.lockers;

CREATE TRIGGER trg_lockers_set_location
    BEFORE INSERT OR UPDATE OF latitude, longitude ON public.lockers
    FOR EACH ROW
EXECUTE FUNCTION public.set_lockers_location_from_lat_lng();
